language: c
os: linux
dist: focal
services:
  - docker

# Don't build the pyup- or depandabot branches that pyup.io / dependabot creates; it's redundant
# with the PR builds that Travis also does.
branches:
  except:
    - /^pyup-/
    - /^dependabot/

cache:
  directories:
    - $HOME/docker

env:
  global:
    # QUAY_USERNAME and QUAY_PASSWORD for docker image upload
    - secure: "Hgi2ukMmpkCeYzCYAmFmM2+zAfCnRuTVkC1JSCZOPmw2P1w6sQJvhBHiIq6sMm2E41VeyIBOGRq2vtU+PKTf4lzR1/unEYCA0QQ8y781DiOB9ExxTIXX+41B+Er1C34whvcnyy/zzN2AD8eWNWssj0sTMw09hDM1uX+Nr5vWsG6yFEWGldiNx4dcCXGcYq76AZ7D/Jzhjmmjsz1JIAxMTPMkbPE9gRb/qtAEDDpjgCVCOl8rYF/N1hSjaG4wZ3CmRNnUqzPfd3beVVzWiCPt9eetRzGn/rku84FWuxYH08VPciZUE3ConZXYCi+PQ/pvF6KHYcssKRBAIgDlip3KDr5GQfSzXAfG+BjRvPh3kfTSE7EkJ3baGnM1i+oB4CnQjGMKQR9WDGb0qKJqGWuNEVgkdpB7mpqkRIO3JPB1OXAkyjgUwTTJelhQ15sSVfQvgZpoGl+bKpyQ27gKHK3cJyKQQe8GS6SC43KLzFhEckhBUWBSygcZmPCKxx3SZf6AIHvhbyTJlG/PoQE862HwyZhMuYV1pwHQiwR3h5gpvsI6+coHrAE7zkTnfCQ/R4/SfVrio2DqGYTRSigwjDK38f+5L8NBTrVddxrKrH5eEGbnsLLda1aEJ3WsDpf0oIUFBs2oJXOipvsVjwPsEZs9UeI9VFGwyoYUHKw5DeREe58="
    - secure: "E8ZBM6aRt+8hISZP+DeXPaOFOVW6cXRFiHSO5d29cqGTmEr//G549Q/5ph+hznyydeWqgnUPE+7AVZUSNd+UModiB9I8HVUxq5g+TkvLR7goLwhDVaeIFUcfGQGvdm3BOt4iTA3c8huhiOndj1/CW4f1B6Vv3k9L7J9JSd29s1Xj7B+lq7FYjbV0a0bt3Mq9lONKzIxqFlqeflmxjVZ5BJ+1XxAsJFI3PBozH676iTg3K1WzdUczk1GvKrOXTUStHssYxtyzDCetRF9xSjNd8SgIJian2i3epd8qJyOcxLy23Xg7QlntnOKUDPWgCjGYNNzKTVV0G2iusX5hLWr0UXoemaRi/NSQ56wTMCF0IadjqTi0vemO/WPWdafZiezVZr81Om6GgCJmLaUfyh2tHF6IZ4HO7GQkRlJ/Cl8TbM1IGhkouS7uv5XgThXXWqncohcanGOTZaYXOwffUGWK/sIymmtmngWQQKzfCj+ClTyDuXaHsHlDX7S03DVAy4Jn9HAUhy1zkM2esRzNMSLYqYlsZuRdDBJcEIN+oegly2t0IFM6aiN+BmgkcKFCpZGyPM7PnhIQ+3X0ySXaPTBeH1VczZ2YjvbTLyPbc2KMW/k3GJkOzrX/aSvtzCXgKfDfkbrIBVewQJ95P5P1sTMCNb3AJICz74+mzx2biviFGfY="

# use YAML aliases and anchors to avoid duplication in stages
# c.f. https://github.com/travis-ci/travis-ci/issues/8295#issuecomment-454457787
_manylinux-build: &manylinux-build
      stage: "Build manylinux images"
      before_install: travis-ci/load_cached_images.sh combined
      script: PLATFORM=$PLATFORM POLICY=$POLICY TRAVIS_COMMIT=$TRAVIS_COMMIT ./build.sh glibc_skip
      deploy:
        provider: script
        script: ./deploy.sh
        on:
          branch: pep600-mayeut
          repo: mayeut/manylinux

jobs:
  include:
    - stage: "Build patched i686 glibc for manylinux2010_x86_64 image"
      arch: amd64
      env: PLATFORM="x86_64" POLICY="manylinux2010"
      before_install: travis-ci/load_cached_images.sh 32
      script: PLATFORM=$PLATFORM manylinux2010_x86_64_glibc/build.sh 32
      before_cache: travis-ci/cache_images.sh 32
    - stage: "Build patched x86_64 glibc for manylinux2010_x86_64 image"
      arch: amd64
      env: PLATFORM="x86_64" POLICY="manylinux2010"
      before_install: travis-ci/load_cached_images.sh 64
      script: PLATFORM=$PLATFORM manylinux2010_x86_64_glibc/build.sh 64
      before_cache: travis-ci/cache_images.sh 64
    - stage: "Add patched glibc to manylinux2010_x86_64 base image"
      arch: amd64
      env: PLATFORM="x86_64" POLICY="manylinux2010"
      before_install: travis-ci/load_cached_images.sh all
      script: PLATFORM=$PLATFORM manylinux2010_x86_64_glibc/build.sh all
      before_cache: travis-ci/cache_images.sh combined
    - <<: *manylinux-build
      arch: amd64
      env: PLATFORM="x86_64" POLICY="manylinux2010"
    - <<: *manylinux-build
      arch: amd64
      env: PLATFORM="x86_64" POLICY="manylinux2014"
    - <<: *manylinux-build
      arch: amd64
      env: PLATFORM="x86_64" POLICY="manylinux_2_24"
    - <<: *manylinux-build
      arch: amd64
      env: PLATFORM="i686" POLICY="manylinux2010"
    - <<: *manylinux-build
      arch: amd64
      env: PLATFORM="i686" POLICY="manylinux2014"
    - <<: *manylinux-build
      arch: amd64
      env: PLATFORM="i686" POLICY="manylinux_2_24"
    - <<: *manylinux-build
      arch: arm64-graviton2
      virt: vm
      group: edge
      env: PLATFORM="aarch64" POLICY="manylinux2014"
    - <<: *manylinux-build
      arch: arm64-graviton2
      virt: vm
      group: edge
      env: PLATFORM="aarch64" POLICY="manylinux_2_24"
    - <<: *manylinux-build
      arch: ppc64le
      env: PLATFORM="ppc64le" POLICY="manylinux2014"
    - <<: *manylinux-build
      arch: ppc64le
      env: PLATFORM="ppc64le" POLICY="manylinux_2_24"
    - <<: *manylinux-build
      arch: s390x
      env: PLATFORM="s390x" POLICY="manylinux2014"
    - <<: *manylinux-build
      arch: s390x
      env: PLATFORM="s390x" POLICY="manylinux_2_24"
