#!/bin/bash

set -eu

case "${MANYLINUX_BUILDARCH:-}" in
  x86_64|amd64) export PATH="/opt/clang-static-x86_64/bin:${PATH}";;
  aarch64|arm64) export PATH="/opt/clang-static-aarch64/bin:${PATH}";;
	*) ;;
esac

if [ "${AUDITWHEEL_ARCH}" == "i686" ] && [ "$(uname -m)" == "x86_64" ]; then
	linux32 "$@"
elif [ "${AUDITWHEEL_ARCH}" == "armv7l" ] && [ "$(uname -m)" != "armv7l" ]; then
	if [ "$(linux32 uname -m)" == "armv8l" ]; then
		export _PYTHON_HOST_PLATFORM="linux-armv7l"
	fi
	linux32 "$@"
else
	exec "$@"
fi
